#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("mirror.Droid.Resource", IsApplication=true)]

namespace mirror.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int bright_icon = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int container = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int darken = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int flip = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int lighten = 2131099651;
			
			// aapt resource value: 0x7f06000a
			public const int myButton = 2131099658;
			
			// aapt resource value: 0x7f060002
			public const int settings = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int texture = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int zoom_icon = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int zoom_in = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int zoom_out = 2131099657;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_camera = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment_mirror = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow_down = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow_up = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bright = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int flip = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int settings = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int zoom = 2130837510;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int frip_mode = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int mirror_mode = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int pause = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int picture = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int settings_appname = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int settings_general = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int settings_site = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int settings_support = 2131034119;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int preferences = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
